<?php

namespace MarincsakIstvan\ApiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RobotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RobotRepository extends EntityRepository
{
}
